# Generated by Django 5.0.7 on 2024-07-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('l_name', models.CharField(max_length=50)),
                ('f_name', models.CharField(max_length=50)),
                ('birthday', models.DateTimeField(blank=True, null=True)),
                ('post', models.CharField(blank=True, max_length=250)),
                ('phone', models.IntegerField(blank=True, max_length=20)),
            ],
        ),
    ]
